import Foundation
import Security

enum KeychainHelper {
    static let cohereAPIKeyService = "io.iremia.cohere-api-key"

    static func get(_ service: String) -> String? {
        let query: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: service,
            kSecReturnData as String: true,
            kSecMatchLimit as String: kSecMatchLimitOne
        ]
        var item: AnyObject?
        let status = SecItemCopyMatching(query as CFDictionary, &item)
        guard status == errSecSuccess, let data = item as? Data else { return nil }
        return String(data: data, encoding: .utf8)
    }

    static func set(_ value: String, service: String) {
        let data = Data(value.utf8)
        let query: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: service
        ]
        SecItemDelete(query as CFDictionary)
        var attrs = query
        attrs[kSecValueData as String] = data
        SecItemAdd(attrs as CFDictionary, nil)
    }

    /// Reads COHERE_API_KEY from the bundled Secrets.plist (generated by
    /// scripts/generate-secrets.sh from .env at build time) and seeds the
    /// Keychain on first launch. No-op if Keychain already has a key or
    /// Secrets.plist has no value.
    static func seedCohereKeyFromBundleIfNeeded() {
        if let existing = get(cohereAPIKeyService), !existing.isEmpty { return }
        guard let url = Bundle.main.url(forResource: "Secrets", withExtension: "plist"),
              let data = try? Data(contentsOf: url),
              let plist = try? PropertyListSerialization.propertyList(from: data, format: nil) as? [String: Any],
              let key = plist["COHERE_API_KEY"] as? String,
              !key.isEmpty else { return }
        set(key, service: cohereAPIKeyService)
    }
}
